spring:
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 1000
            response-timeout: 10s
          routes:
            - id: monolith-api
              uri: lb://monolith
              predicates:
                - Path=/api/v1/**,/v3/api-docs/**,/swagger-ui/**,/swagger-ui.html
