spring:
  application:
    name: production-service
  datasource:
    url: ${PRODUCTION_DB_URL:jdbc:postgresql://production-postgres:5432/production}
    username: ${PRODUCTION_DB_USER:production}
    password: ${PRODUCTION_DB_PASSWORD:production-dev}
    hikari:
      connection-timeout: 5000
      validation-timeout: 3000
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-migration-naming: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC


---
spring:
  cloud:
    openfeign:
      client:
        config:
          order-service:
            connectTimeout: 1000
            readTimeout: 2000
    circuitbreaker:
      resilience4j:
        disable-time-limiter: true
        disable-thread-pool: true
resilience4j:
  circuitbreaker:
    instances:
      order:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        ignoreExceptions:
          - ru.itmo.highload.catering.common.error.ApiException
